/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hq_bean_LedNative */

#ifndef _Included_com_hq_bean_LedNative
#define _Included_com_hq_bean_LedNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hq_bean_LedNative
 * Method:    openDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hq_bean_LedNative_openDev
  (JNIEnv *, jobject);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    devOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hq_bean_LedNative_devOn
  (JNIEnv *, jobject);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    devOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hq_bean_LedNative_devOff
  (JNIEnv *, jobject);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    closeDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hq_bean_LedNative_closeDev
  (JNIEnv *, jobject);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    addNum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hq_bean_LedNative_GetPWD
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hq_bean_LedNative_getStringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    setStringToJni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hq_bean_LedNative_setStringToJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    getStudent
 * Signature: ()Lcom/hq/bean/Student;
 */
JNIEXPORT jobject JNICALL Java_com_hq_bean_LedNative_getStudent
  (JNIEnv *, jobject);

/*
 * Class:     com_hq_bean_LedNative
 * Method:    setStudent
 * Signature: (Lcom/hq/bean/Student;)V
 */
JNIEXPORT void JNICALL Java_com_hq_bean_LedNative_setStudent
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
